### PR TITLE
Improve Ui

### PR DESCRIPTION
**Pull request by AsianCat54x**
Improved Ui by adding colors, and user inputs via choices.

Updated Ui Image:

### CODE REVIEW

**Comment by Ayush-Singh-Code** [comment]
I want your help in one more project 

Repository name: Project math

You can help to improve its ui too 
If you are intrested mail me at
aayushsingh.code@gmail.com

**Comment by AsianCat54x** [comment]
Alright I will improve the ui there too. However, are you going to merge this pull request?

**Comment by Ayush-Singh-Code** [comment]
yes

**Comment by AsianCat54x** [comment]
Thanks for accepting my pull request. I will surely improve ui. However, it would be better if you try to do it yourself and if there are errors, I will help you out ;)

**Comment by Ayush-Singh-Code** [comment]
I like your suggestion I will improve it myself

**Comment by AsianCat54x** [comment]
Just mail me at asiancat75x@gmail.com. I would be glad to help you out!

**Comment by Ayush-Singh-Code** [comment]
The changes that you have made when I run the code in vs code it looks something like this
image

**Comment by AsianCat54x** [comment]
Are you on windows?

**Pull request merged**
